### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/docs.sailscasts.com#3]

**Comment by lennyAiko** [comment]
Does this mean to eliminate the existing license, and generate one for MIT? @DominusKelvin @poriacodes

**Comment by lennyAiko** [comment]
The LICENSE is already an MIT LICENSE

**Comment by DominusKelvin** [comment]
Thanks for the heads up @lennyAiko I will go ahead and close this issue
